# Generated by Django 4.2 on 2023-04-18 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('account_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PublicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('office_hours', models.CharField(max_length=25)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=25)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
                ('ta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grader', models.BooleanField(null=True)),
                ('number_of_labs', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
                ('ta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user'),
        ),
    ]
