# Generated by Django 4.1.7 on 2023-04-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user'),
        ),
        migrations.AlterField(
            model_name='courseta',
            name='is_grader',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseta',
            name='number_of_labs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='ta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user'),
        ),
    ]
